name: turismo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15

  mime: ^1.0.0

  http_parser: ^4.0.0

  image_picker: ^0.8.7+4
  # Para manejar HTTP requests
  http: ^0.13.5
  # Para manejar estado en la app
  provider: ^6.0.5

  # Para validaciones de formularios
  validators: ^3.0.0

  # Para diseño más limpio y responsive
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  pdf: ^3.10.1
  printing: ^5.12.5

  fl_chart: ^0.70.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true